# Generated by Django 4.2.2 on 2023-07-02 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesscalculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, verbose_name='Имя')),
                ('surname', models.CharField(db_index=True, max_length=63, verbose_name='Фамилия')),
                ('last_name', models.CharField(blank=True, max_length=63, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('password', models.CharField(default='Null', max_length=63, verbose_name='Пароль')),
                ('city', models.CharField(max_length=63, verbose_name='Город')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('registration_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(default='boya@;ist.ru', max_length=254, verbose_name='Почта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='registration_date',
            field=models.DateField(auto_now_add=True, default='2020-02-02'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='tel',
            field=models.CharField(default='89625013268', max_length=12, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='activity',
            field=models.CharField(max_length=255, verbose_name='Основная деятельность'),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(max_length=31, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='company',
            name='form',
            field=models.CharField(max_length=3, verbose_name='Форма организации'),
        ),
        migrations.AlterField(
            model_name='company',
            name='founder',
            field=models.CharField(max_length=63, verbose_name='Основатель'),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(max_length=255, verbose_name='Сфера деятельности'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(db_index=True, max_length=63, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='company',
            name='year',
            field=models.IntegerField(verbose_name='Год основания'),
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('year', models.IntegerField(verbose_name='Отчетный год')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('revenue', models.IntegerField(verbose_name='Выручка')),
                ('returns', models.IntegerField(verbose_name='Затраты')),
                ('oper_exp', models.IntegerField(verbose_name='Коммерческие расходы')),
                ('other_costs', models.IntegerField(verbose_name='Прочие расходы')),
                ('taxes', models.IntegerField(verbose_name='Налоги')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesscalculator.company')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=2047, verbose_name='Рекомендации')),
                ('date', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesscalculator.company')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesscalculator.expert')),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('year', models.IntegerField(verbose_name='Отчетный год')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('current_assets', models.IntegerField(verbose_name='Оборотные активы')),
                ('fixed_assets', models.IntegerField(verbose_name='Внеоборотные активы')),
                ('equity', models.IntegerField(verbose_name='Собственный капитал')),
                ('current_liabilities', models.IntegerField(verbose_name='Текущие обязательства')),
                ('long_liabilities', models.IntegerField(verbose_name='Долгосрочные обязательства')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesscalculator.company')),
            ],
        ),
    ]
