# Generated by Django 4.2.2 on 2023-07-02 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesscalculator', '0002_expert_company_email_company_registration_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balance',
            options={'ordering': ['-date', 'company'], 'verbose_name': 'Бухгалтерский баланс', 'verbose_name_plural': 'Бухгалтерские балансы'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-registration_date', 'name'], 'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='expert',
            options={'ordering': ['-registration_date', 'surname'], 'verbose_name': 'Эксперт', 'verbose_name_plural': 'Эксперты'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-date', 'company'], 'verbose_name': 'Рекомендация', 'verbose_name_plural': 'Рекомендации'},
        ),
        migrations.AlterModelOptions(
            name='statement',
            options={'ordering': ['-date', 'company'], 'verbose_name': 'Отчет о финансовых результатах', 'verbose_name_plural': 'Отчеты о финансовых результатах'},
        ),
        migrations.AlterField(
            model_name='balance',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesscalculator.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='report',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesscalculator.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='report',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesscalculator.expert', verbose_name='Эксперт'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesscalculator.company', verbose_name='Компания'),
        ),
    ]
