# Generated by Django 4.2.2 on 2023-07-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesscalculator', '0004_report_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='select',
            field=models.CharField(choices=[('0', '0'), ('1', '1')], max_length=15, verbose_name='Выбор отчета'),
        ),
    ]
