# Generated by Django 4.2.2 on 2023-07-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesscalculator', '0005_alter_report_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='select',
            field=models.BooleanField(choices=[('0', 'Балалнс'), ('1', 'ОФР')], max_length=15, verbose_name='Выбор отчета'),
        ),
    ]
