# Generated by Django 4.2.2 on 2023-07-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesscalculator', '0006_alter_report_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='select',
            field=models.BooleanField(choices=[(True, 'Балалнс'), (False, 'ОФР')], max_length=15, verbose_name='Выбор отчета'),
        ),
    ]
