# Generated by Django 4.2.2 on 2023-07-10 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("businesscalculator", "0008_company_user_alter_report_select"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="user",
        ),
    ]
